### PR TITLE
fix(BookController.java): remove unnecessary redirect attribute

### LINKED ISSUE #82: The delete book end-point must be changed to a POST request
We are currently using a GET request to delete books, this must be changed to a POST request.

### PR DESCRIPTION
**Pull request by zaidoon1**
Fixes #82 

## Description of changes
Removed unnecessary redirect attribute that was appending extra parameters in the URL.

## Screenshots (If Applicable)
N/A

## Checklist
- [ ] I have unit tested my code.
- [ ] I have integration tested my code.
- [X] All new and existing tests passed.
- [ ] I have [updated the diagrams](https://github.com/amazin-team/Amazin-online-bookstore/wiki/Updating-the-diagrams) ModelsUMLClassDiagram and EntityRelationshipDiagram (if necessary).

### CODE REVIEW

**Review by abungay — APPROVED** [review]

**Review by MohamedZalat — APPROVED** [review]

File: src/main/java/amazin/controller/BookController.java [hunk 1]
```diff
@@ -56,15 +55,12 @@ public String addBookForm(Model model) {
     }
 
     @PostMapping("/addbook")
-    public String addBook(@Valid @ModelAttribute(MODEL_ATTRIBUTE_BOOK) Book book, BindingResult result,
```
Comment (LauraMachado21) [inline src/main/java/amazin/controller/BookController.java:59]: Nice refactoring! I was wondering why we needed this parameter.
